# SPDX-FileCopyrightText: Stone Tickle <lattis@mochiro.moe>
# SPDX-License-Identifier: GPL-3.0-only

name: vs2019

on:
  push:
    branches:
      - master
      - '[0-9]+.[0-9]+'
  pull_request:
    branches: [master]
    types: [opened, synchronize, reopened]

jobs:
  test:
    strategy:
      matrix:
        arch:
          - amd64
          - amd64_x86
        compiler:
          # TODO: Add clang when bootstrap.bat adds clang support.
          - msvc
    name: ${{ matrix.arch }} - ${{ matrix.compiler }}
    runs-on: windows-2019
    defaults:
      run:
        shell: cmd
    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}
      - name: bootstrap
        env:
          GIT_HTTP_USER_AGENT: "git/2.0.0 (for:~lattis/muon; contact:lattis@mochiro.moe)"
        run: >
          bootstrap.bat build
          && build\muon-bootstrap.exe -v setup build
          && build\muon-bootstrap.exe -vC build samu
      - name: test
        run: >
          build\muon.exe -vC build test
          || exit 0
      - name: upload-binary
        shell: bash
        env:
          GH_DEPLOY: 1
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/deploy
          chmod 600 ~/.ssh/deploy
          cat >> ~/.ssh/config <<EOF
          Host mochiro.moe
              IdentityFile ~/.ssh/deploy
              IdentitiesOnly yes
          EOF
          . "build/version.sh"
          exe_name="muon-$version-amd64-win.exe"
          dest_dir="muon/releases/$version"
          ssh \
            -o StrictHostKeyChecking=no\
            -p 2975\
            deploy@mochiro.moe\
            "sh -c 'mkdir -p \"$dest_dir\"; cat -> \"$dest_dir/$exe_name\"'"\
            < "build/muon.exe"
        if: matrix.arch == 'amd64' && github.event_name != 'pull_request'
